apiVersion: batch/v1
kind: Job
metadata:
  generateName: load-
  labels:
    app: load
  namespace: load
spec:
  parallelism: 5
  template:
    spec:
      serviceAccountName: statement-demo
      containers:
      - name: load
        image: 837108680928.dkr.ecr.us-east-1.amazonaws.com/load:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /tmp/application-aws.properties
          name: config
          subPath: application-aws.properties
        resources:
          limits:
            memory: "1Gi"
            cpu: 1
          requests:
            memory: "1Gi"
            cpu: 1
        env:
        - name: KAFKA_BOOTSTRAP
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: bootstrap
        - name: TOTAL_CONTAS
          value: "266670"
        - name: DIAS_POR_CONTA
          value: "30"
        - name: ULTIMO_DIA
          value: "2020-10-31"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - configMap:
          name: application.properties
        name: config
      restartPolicy: Never
  backoffLimit: 0